spring:
  application:
    name: sample

server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: utf-8
      force: true

mybatis:
  mapper-locations:
    - classpath*:/mappers/*.xml

logging:
  level:
    root: INFO
    com.simple.mybatis: DEBUG
  file:
    name: log/out.log
  logback:
    rollingpolicy:
      max-history: 3
  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} [%X{requestId}] %clr(%5p) %clr([%13.13t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} [%X{requestId}] %clr(%5p) ${PID:- } %clr([%13.13t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

knife4j:
  enable: true
  openapi:
    title: Sample Api
    description: "Sample Api"
    email: clarence.c.xu@foxmail.com
    concat: FanXing
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      web:
        group-name: web
        api-rule: package
        api-rule-resources:
          - com.simple.mybatis.sample.controller